version: "3"

services:
  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:v21.9.5
    hostname: "redpanda-${PROJECT_NAME}"
    container_name: "redpanda-${PROJECT_NAME}"
    ports:
      - "9092:9092"
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    networks:
      - local-network
  
  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: kafdrop-${PROJECT_NAME}
    ports:
      - "9000:9000"
    depends_on:
      - redpanda
    environment:
      KAFKA_BROKERCONNECT: redpanda:29092
    networks:
      - local-network
  
  #TODO: Add control-center
  
networks:
  local-network:
    name: network-${PROJECT_NAME}